# 使用するベースイメージ
FROM node:21-alpine

# コンテナ内での作業ディレクトリを設定
WORKDIR /app

# ローカルのファイルをコンテナにコピー
COPY frontend/package.json ./
COPY frontend/package-lock.json ./

RUN npm install

COPY frontend/ .

RUN npm run build

CMD ["/bin/sh"]
