FROM golang:latest

# Install Air
RUN go install github.com/cosmtrek/air@latest

WORKDIR /app/backend

COPY backend .
RUN go mod tidy
RUN go mod download

# Run Air for hot reloading
CMD ["air", "-c", ".air.toml"]

